//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventarioIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plaza()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int IdPlaza { get; set; }
        public string Nombre_Plaza { get; set; }
        public string Descripcion { get; set; }
        public bool Estado_Plaza { get; set; }
        public int Ubicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
